<?php
require_once('../Include/DbConnector.php');  
require_once('../Include/SqlInjection.php');  
require_once('../Include/phpscripts.php');  
$data         = ""; 
$company_logo = '../uploads/company_logo/Autostrad_logo.png';
$booking_id    = $_REQUEST['flag'];
if(!empty($booking_id)){
 $sql          = "SELECT tb1.*,tb2.`broker_name`,tb3.`location_name` AS `pickup_location`,tb4.`location_name` AS `return_location`,tb5.`vehicle_name` AS `vehicle_name`,tb5.`sipp_code` AS `sipp_code`,tb6.`group_name` AS `group_name`,tb7.`transmission_name` AS `transmission_name`,tb8.`category_name` AS `category_name`,tb5.`doors` AS `doors`,tb5.`passengers` AS `passengers`, CASE WHEN tb5.`air_conditionar`=0 THEN 'Non A/C' WHEN tb5.`air_conditionar`=1 THEN 'A/C' ELSE 'A/C' END AS `air_conditionar`, tb3.`location_email` AS `location_email`,tb4.`location_email` AS `dropoff_location_email` FROM `tbl_bms_booking` tb1 LEFT JOIN `tbl_bms_broker_master` tb2 ON tb1.`broker_id`=tb2.`broker_id`  LEFT JOIN `tbl_bms_location_master` tb3 ON tb1.`pickUpLocation`=tb3.`location_id` LEFT JOIN `tbl_bms_location_master` tb4 ON tb1.`returnLocation`=tb4.`location_id` LEFT JOIN `tbl_bms_vehicle_master` tb5 ON tb1.`vehicle_id`=tb5.`vehicle_id` LEFT JOIN `tbl_bms_group_master` tb6 ON tb5.`group_id`=tb6.`group_id` LEFT JOIN `tbl_bms_transmission_master` tb7 ON tb5.`transmission_id`=tb7.`transmission_id` LEFT JOIN `tbl_bms_category_master` tb8 ON tb5.`category_id`=tb8.`category_id` WHERE tb1.`booking_id`='$booking_id'";
$data = mysqli_query($conn,$sql);
if(mysqli_num_rows($data)>0){
while($build = mysqli_fetch_array($data)){ 

  $broker_name         = $build['broker_name'];
  $reservation_no      = $build['reservation_no'];
  $externalReference   = $build['externalReference'];
  $flightNumber        = $build['flightNumber'];
  $entered_date        = $build['entered_date'];
  $customerName        = $build['customerName'];
  $customerPhone       = $build['customerPhone'];
  $customerEmail       = $build['customerEmail'];
  
  $pickUpDate         = date('d.M.Y H:i:s',strtotime($build['pickUpDate']));
  $returnDate         = date('d.M.Y H:i:s',strtotime($build['returnDate']));
   
  $pickup_location     = $build['pickup_location'];
  $return_location     = $build['return_location'];
  $location_email      = $build['location_email'];
  $dropoff_location_email      = $build['dropoff_location_email'];
  $vehicle_name        = $build['vehicle_name'];
  $sipp_code           = $build['sipp_code'];
  $group_name          = $build['group_name'];
  $transmission_name   = $build['transmission_name'];
  $category_name       = $build['category_name'];
  $doors               = $build['doors'];
  $passengers          = $build['passengers'];
  $air_conditionar     = $build['air_conditionar'];
  
  $totalValue                    = $build['totalValue'];
  $totalValueWithoutAccssories   = $build['totalValueWithoutAccssories'];
  $noOfDays                      = $build['noOfDays'];
  $accessories                   = $build['accessories'];
  
  $entered_date = date('d.M.Y H:i:s',strtotime($build['entered_date']));
  	$status             = $build['status'];
	$status_name        = "";
	if($status == "1") {
	$status_name  = 'Confirmed';
	} else if($status == "2"){
	$status_name  = 'Cancelled';
	}else{
	//do nothing
	}
 }
}

//including files required to print pdf
//=============print pdf tcpdf==================
require_once('../plugins/tcpdf/config/lang/eng.php');
require_once('../plugins/tcpdf/tcpdf.php');
require('../plugins/tcpdf/htmlcolors.php');
$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
/***************Custom Footer Template****************/
// Extend the TCPDF class to create custom Footer
class MYPDF extends TCPDF {
    // Page footer
    public function Footer() {
        // Position at 15 mm from bottom
        //$this->SetY(-50);
		// Add a footer line 
		$this->writeHTML('<hr>', true, false, false, false, '');
        // Set font
        $this->SetFont('times', '', 10);
        // Page number
		$this->Cell(0, 10, 'Please note that this is an autogenerated receipt.', 0, false, 'C', 0, '', 0, false, 'T', 'M');
        //$this->Cell(0, 10, 'Page '.$this->getAliasNumPage().'/'.$this->getAliasNbPages(), 0, false, 'L', 0, '', 0, false, 'T', 'M');
    }
}
$pdf = new MYPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
/***************Custom Footer Template****************/

$pdf->SetCreator(PDF_CREATOR);
$pdf->SetTextColor($col1 = 5,$col2 = -1,$col3 = -1,$col4 = -1,$ret = false,$name = '');	
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));
// set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);
//set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);
//set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);
//set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);
//set some language-dependent strings
$pdf->setLanguageArray($l);
$pdf->setPageOrientation("P");
//$pdf->SetFont('freesans', '', 12);
$pdf->SetFont('times', '', 10);
$pdf->SetMargins(9, true);
$pdf->AddPage(); 

//if ($company_logo != '' && file_exists($company_logo)) {
$pdf->writeHTML('<table width="100%" border="0" cellpadding="5"><tr><td align="right"><img src="../uploads/company_logo/Autostrad_logo.jpg" width="100"/></td></tr></table>', true, false, true, false, '');
//}
$pdf->writeHTML('<table width="100%" border="0" cellpadding="1"><tr><td align="center"><h1>Booking Order</h1></td></tr><tr align="right"><td>Reservation No:<b>'.$reservation_no.'</b></td></tr></table>', true, false, true, false, '');
$data = "";

//first session
$data.='<table class="table table-bordered table-striped" width="100%" height="auto" border="1" cellpadding="5" cellspacing="0" style="border-collapse:collapse;border:solid 1px #DDD"><thead><tr><th colspan="2" style="color:red;font-weight:bold;text-align:center;"><b>Reservation & Customer</b></th><th colspan="2" style="color:red;font-weight:bold;text-align:center;"><b>Vehicle</b></th></tr></thead><tbody style="border-collapse:collapse;border:solid 1px #DDD">
                <tr><td style="font-weight:bold;">Broker:</td><td>'.$broker_name.'</td><td style="font-weight:bold;">Vehicle Name:</td><td>'.$vehicle_name.'</td></tr>
				<tr><td style="font-weight:bold;">Confirmation No:</td><td>'.$externalReference.'</td><td style="font-weight:bold;">SIPP Code:</td><td>'.$sipp_code.'</td></tr>
				<tr><td style="font-weight:bold;">Flight No:</td><td>'.$flightNumber.'</td><td style="font-weight:bold;">Vehicle Group:</td><td>'.$group_name.'</td></tr>
				<tr><td style="font-weight:bold;">Booked On:</td><td>'.$entered_date.'</td><td style="font-weight:bold;">Vehicle Class:</td><td>'.$category_name.'</td></tr>
				<tr><td style="font-weight:bold;">Customer Name:</td><td>'.$customerName.'</td><td style="font-weight:bold;">Transmssion:</td><td>'.$transmission_name.'</td></tr>
				<tr><td style="font-weight:bold;">Customer Phone:</td><td>'.$customerPhone.'</td><td style="font-weight:bold;">Doors / Seats:</td><td>'.$doors.' / '.$passengers.'</td></tr>
				<tr><td style="font-weight:bold;">Customer Email:</td><td>'.$customerEmail.'</td><td style="font-weight:bold;">Air Conditionar:</td><td>'.$air_conditionar.'</td></tr></tbody></table>
<table class="table table-bordered table-striped" width="100%" height="auto" border="1" cellpadding="5" cellspacing="0" style="border-collapse:collapse;border:solid 1px #DDD"><thead><tr><th colspan="2" style="color:red;font-weight:bold;text-align:center;"><b>Location</b></th><th colspan="2" style="color:red;font-weight:bold;text-align:center;"><b>Cost of rental</b></th></tr></thead><tbody style="border-collapse:collapse;border:solid 1px #DDD">
                <tr><td style="font-weight:bold;">Pick-up date & time:</td><td>'.$pickUpDate.'</td><td style="font-weight:bold;">Status:</td><td>'.$status_name.'</td></tr>
				<tr><td style="font-weight:bold;">Pick-up location:</td><td>'.$pickup_location.'</td><td style="font-weight:bold;">Accessories:</td><td>'.$accessories.'</td></tr>
				<tr><td style="font-weight:bold;">Return date & time:</td><td>'.$returnDate.'</td><td style="font-weight:bold;">No Of Days:</td><td>'.$noOfDays.'</td></tr>
				<tr><td style="font-weight:bold;">Return location:</td><td>'.$return_location.'</td><td style="font-weight:bold;">Total:<br/></td><td><br/>AED '.$totalValue.'</td></tr><tr><td style="font-weight:bold;" colspan="2"></td><td style="font-weight:bold;">Net Rate:<br/></td><td><br/>AED '.$totalValueWithoutAccssories.'</td></tr></tbody></table>';

$data.='';
$data = utf8_encode($data);
$pdf->writeHTML($data, true, false, true, false, '');     
//=========================last page=============//
$pdf->lastPage();
$pdfnamenew   = "invoice_".$reservation_no."_".date("d_m_Y_h_i_s").".pdf";  
ob_end_clean();
$pdf->Output($pdfnamenew, 'D');
}
//$pdfnamenew_s = $pdf->Output($pdfnamenew, "S");
//exit();
?>
