<?php
require_once('../Include/DbConnector.php');  
require_once('../Include/SqlInjection.php');  
require_once('../Include/phpscripts.php');  
$data         = ""; 
$company_logo = '../uploads/company_logo/Autostrad_logo.png';
$ind_premium_id        = $_REQUEST['flag'];
if(!empty($ind_premium_id)){
//=============print pdf tcpdf==================
require_once('../plugins/tcpdf/config/lang/eng.php');
require_once('../plugins/tcpdf/tcpdf.php');
require('../plugins/tcpdf/htmlcolors.php');
$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
/***************Custom Footer Template****************/
// Extend the TCPDF class to create custom Footer
class MYPDF extends TCPDF {
    // Page footer
    public function Footer() {
        // Position at 15 mm from bottom
        //$this->SetY(-50);
		// Add a footer line 
		//$this->writeHTML('<hr>', true, false, false, false, '');
        // Set font
       // $this->SetFont('calibri', '', 10);
        // Page number
		//$this->Cell(0, 10, 'Please note that this is an autogenerated receipt.', 0, false, 'C', 0, '', 0, false, 'T', 'M');
        //$this->Cell(0, 10, 'Page '.$this->getAliasNumPage().'/'.$this->getAliasNbPages(), 0, false, 'L', 0, '', 0, false, 'T', 'M');
    }
}

$pdf = new MYPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
/***************Custom Footer Template****************/

$pdf->SetCreator(PDF_CREATOR);
$pdf->SetTextColor($col1 = 5,$col2 = -1,$col3 = -1,$col4 = -1,$ret = false,$name = '');	
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));
// set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);
//set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);
//set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);
//set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);
//set some language-dependent strings
$pdf->setLanguageArray($l);
$pdf->setPageOrientation("P");
//$pdf->SetFont('freesans', '', 12);
$pdf->SetFont('calibri', '', 10);

$pdf->SetMargins(9,9,9, true);
$pdf->AddPage(); 
$color_array = array('#92CCA6','#3B71CA','#9FA6B2','#14A44D','#DC4C64','#E4A11B','#54B4D3','#332D2D');
$new_array   = array();
	
	$Query = "SELECT tb1.*,tb2.`full_name`,tb2.`email` FROM `tbl_cmt_ind_premium_transactions` tb1 LEFT JOIN `tbl_login` tb2 ON tb1.`entered_by`=tb2.`user_id` WHERE  tb1.`ind_premium_id`='$ind_premium_id'";
	$sqlQ  = mysqli_query($conn,$Query);
    while($build = mysqli_fetch_array($sqlQ)){
    $today               = date("Y-m-d");
	$tr_no               = killstring($build['tr_no']);
	$customer_full_name  = killstring($build['customer_name']);
	$batch_name          = killstring($build['tr_no']);
   /* $cnt_company          = 0;
	$company_id_now       = $_REQUEST['company_id'];
	$cnt_company          = count($company_id_now);*/
	$gender                  = killstring($build['customer_gender']);
	$marital_status          = killstring($build['customer_marital_status']);
	$residency               = killstring($build['customer_emirate_id']);
	$customer_dob            = killstring($build['customer_dob']);
	
	$entered_full_name       = killstring($build['full_name']);
	$entered_email           = killstring($build['email']);
	$entered_date            = date('d-m-Y',strtotime($build['entered_date']));
/*	$additionl_customer_full_name_now       = $_REQUEST['additionl_customer_full_name'];
	$cnt_additionl_customer                 = count($additionl_customer_full_name_now);*/
	
	$start_date           = date('Y-m-d',strtotime($build['ins_start_date']));
	$start_date_now       = date('d-m-Y',strtotime($build['ins_start_date']));
	$dob_primary  = date('Y',strtotime($customer_dob));
    $year         = date('Y');
    $age_primary  = ($year - $dob_primary);
    $today = date('d-m-Y');
	}

$pdf->writeHTML('<br/><br /><table width="100%" border="0" cellpadding="3" cellspacing="0"><tr><td>Client Name<br>'.$customer_full_name.'</td><td>Advisor<br>'.$entered_full_name.'</td><td>Contact<br>'.$entered_email.'</td></tr><tr><td>Quote Date<br>'.$entered_date.'</td><td>Start Date<br>'.$start_date_now.'</td><td><img src="../uploads/company_logo/colemont_logo.jpg" width="100"/></td></tr></table>', true, false, true, false, '');

$data = ""; 	
$data.='
     <table  class="table table-bordered table-striped" width="100%" height="auto" border="1" cellpadding="3" cellspacing="0" style="border-collapse:collapse;border:solid 0.5px #DDD;">
      <thead>
        <tr>
          <th></th>';
		  $sqlQryA             = mysqli_query($conn,"SELECT tb2.`company_name` FROM `tbl_cmt_ind_companies` tb1 LEFT JOIN `tbl_cmt_ins_company_master` tb2 ON tb1.`company_id`=tb2.`company_id` WHERE tb1.`tr_no`='$tr_no' ORDER BY tb2.`company_name` ASC");
		  $cnt_company = !empty(mysqli_num_rows($sqlQryA))?mysqli_num_rows($sqlQryA):0;
		  while($row = mysqli_fetch_array($sqlQryA)){
		  $company_name        = empty($row['company_name'])?0:$row['company_name'];
		  $randomn_array = $color_array[array_rand($color_array)];
		  array_push($new_array,$randomn_array);
          $data.='<th style="background-color:'.$randomn_array.';color:white;font-weight:bold;">'.$company_name.'</th>';
		  }
        $data.='</tr>
      </thead>
      <tbody>
      <tr>
      <td>Plan Name</td>';
							    $sqlQryAB             = mysqli_query($conn,"SELECT tb2.`company_name`,tb1.`company_id`,tb1.`price_batch_id`,tb1.`premium_id` FROM `tbl_cmt_ind_companies` tb1 LEFT JOIN `tbl_cmt_ins_company_master` tb2 ON tb1.`company_id`=tb2.`company_id` WHERE tb1.`tr_no`='$tr_no' ORDER BY tb2.`company_name` ASC");
		                        while($row = mysqli_fetch_array($sqlQryAB)){
								$company_id          = $row['company_id'];
								$price_batch_id      = $row['price_batch_id'];
								$premium_id          = $row['premium_id'];
								$sqlQryA             = mysqli_query($conn,"SELECT `premium_name` FROM `tbl_cmt_premium_master` WHERE `premium_id`='$premium_id'");
								$rowQryA             = mysqli_fetch_row($sqlQryA);
								$premium             = empty($rowQryA[0])?" ":$rowQryA[0];
								echo  $data.='<td>'.$premium.'</td>';
		  }
		  $data.='</tr>
          <tr>
          <td>Direct Billing Network</td>';
							   $sqlQryAB             = mysqli_query($conn,"SELECT tb2.`company_name`,tb1.`company_id`,tb1.`billing_network` FROM `tbl_cmt_ind_companies` tb1 LEFT JOIN `tbl_cmt_ins_company_master` tb2 ON tb1.`company_id`=tb2.`company_id` WHERE tb1.`tr_no`='$tr_no' ORDER BY tb2.`company_name` ASC");
		                        while($row = mysqli_fetch_array($sqlQryAB)){
								$company_id          = $row['company_id'];
								$billing_network     = $row['billing_network'];
								$sqlQryA             = mysqli_query($conn,"SELECT `billing_network`, `billing_network_id` FROM `tbl_cmt_ins_direct_billing_network_master` WHERE `billing_network_id`='$billing_network'");
								$rowQryA             = mysqli_fetch_row($sqlQryA);
								$billing_network     = empty($rowQryA[0])?" ":$rowQryA[0];
								 $data.='<td>'.$billing_network.'</td>';
		  }
      $data.='</tr>
       <tr>
        <td>Deductible / Co-pay</td>';
							    $sqlQryAB             = mysqli_query($conn,"SELECT tb2.`company_name`,tb1.`company_id`,tb1.`deductable_copay` FROM `tbl_cmt_ind_companies` tb1 LEFT JOIN `tbl_cmt_ins_company_master` tb2 ON tb1.`company_id`=tb2.`company_id` WHERE tb1.`tr_no`='$tr_no' ORDER BY tb2.`company_name` ASC");
		                        while($row = mysqli_fetch_array($sqlQryAB)){
								$company_id          = $row['company_id'];
								$deductable_copay     = $row['deductable_copay'];
								$sqlQryA             = mysqli_query($conn,"SELECT `deductable_copay`, `deductable_copay_id` FROM `tbl_cmt_ins_deductable_copay_master` WHERE `deductable_copay_id`='$deductable_copay'");
								$rowQryA             = mysqli_fetch_row($sqlQryA);
								$deductable_copay     = empty($rowQryA[0])?" ":$rowQryA[0];
								$data.='<td>'.$deductable_copay.'</td>';
		  }
       $data.='</tr>
        <tr style="background:#CF9;">
        <td><b>Benefits Guide</b></td>';
         for($i=0; $i < $cnt_company; $i++){
          $data.='<td></td>';
		  }
       $data.='</tr>
        <tr>
        <td>Annual Limit</td>';
							   $sqlQryAB             = mysqli_query($conn,"SELECT tb2.`company_name`,tb1.`company_id`,tb1.`price_batch_id`,tb1.`premium_id`,tb1.`annual_limit` FROM `tbl_cmt_ind_companies` tb1 LEFT JOIN `tbl_cmt_ins_company_master` tb2 ON tb1.`company_id`=tb2.`company_id` WHERE tb1.`tr_no`='$tr_no' ORDER BY tb2.`company_name` ASC");
		                        while($row = mysqli_fetch_array($sqlQryAB)){
								$company_id          = $row['company_id'];
								$price_batch_id      = $row['price_batch_id'];
								$premium_id          = $row['premium_id'];
								$annual_limit        = $row['annual_limit'];
								/*$sqlQryA             = mysqli_query($conn,"SELECT `annual_limit` FROM `tbl_cmt_premium_master` WHERE `premium_id`='$premium_id'");
								$rowQryA             = mysqli_fetch_row($sqlQryA);
								$annual_limit             = empty($rowQryA[0])?" ":$rowQryA[0];*/
								$data.='<td>AED'.Checkvalid_number_or_not($annual_limit,2).'</td>';
		  }
      $data.='</tr>
        <tr>
        <td>Geographical Coverage</td>';
							   $sqlQryAB             = mysqli_query($conn,"SELECT tb2.`company_name`,tb1.`company_id`,tb1.`price_batch_id`,tb1.`premium_id`,tb1.`geographical_coverage` FROM `tbl_cmt_ind_companies` tb1 LEFT JOIN `tbl_cmt_ins_company_master` tb2 ON tb1.`company_id`=tb2.`company_id` WHERE tb1.`tr_no`='$tr_no' ORDER BY tb2.`company_name` ASC");
		                        while($row = mysqli_fetch_array($sqlQryAB)){
								$company_id          = $row['company_id'];
								$price_batch_id      = $row['price_batch_id'];
								$premium_id          = $row['premium_id'];
								$geographical_coverage          = $row['geographical_coverage'];
								/*$sqlQryA             = mysqli_query($conn,"SELECT `geographical_coverage` FROM `tbl_cmt_premium_master` WHERE `premium_id`='$premium_id'");
								$rowQryA             = mysqli_fetch_row($sqlQryA);
								$geographical_coverage             = empty($rowQryA[0])?" ":$rowQryA[0];*/
								$data.='<td>'.$geographical_coverage.'</td>';
		  }
       $data.='</tr>
      <tr>
        <td>Inpatient (Hospitalization)</td>';
							   $sqlQryAB             = mysqli_query($conn,"SELECT tb2.`company_name`,tb1.`company_id`,tb1.`price_batch_id`,tb1.`premium_id`,tb1.`inpatient` FROM `tbl_cmt_ind_companies` tb1 LEFT JOIN `tbl_cmt_ins_company_master` tb2 ON tb1.`company_id`=tb2.`company_id` WHERE tb1.`tr_no`='$tr_no' ORDER BY tb2.`company_name` ASC");
		                        while($row = mysqli_fetch_array($sqlQryAB)){
								$company_id          = $row['company_id'];
								$price_batch_id      = $row['price_batch_id'];
								$premium_id          = $row['premium_id'];
								$inpatient           = $row['inpatient'];
								/*$sqlQryA             = mysqli_query($conn,"SELECT `inpatient` FROM `tbl_cmt_premium_master` WHERE `premium_id`='$premium_id'");
								$rowQryA             = mysqli_fetch_row($sqlQryA);
								$inpatient           = empty($rowQryA[0])?" ":$rowQryA[0];*/
								$data.='<td>'.$inpatient.'</td>';
								
		  }
        $data.='</tr>
      <tr>
        <td>Out Patient</td>';
							   $sqlQryAB             = mysqli_query($conn,"SELECT tb2.`company_name`,tb1.`company_id`,tb1.`price_batch_id`,tb1.`premium_id`,tb1.`out_patient` FROM `tbl_cmt_ind_companies` tb1 LEFT JOIN `tbl_cmt_ins_company_master` tb2 ON tb1.`company_id`=tb2.`company_id` WHERE tb1.`tr_no`='$tr_no' ORDER BY tb2.`company_name` ASC");
		                        while($row = mysqli_fetch_array($sqlQryAB)){
								$company_id          = $row['company_id'];
								$price_batch_id      = $row['price_batch_id'];
								$premium_id          = $row['premium_id'];
								$out_patient         = $row['out_patient'];
								/*$sqlQryA             = mysqli_query($conn,"SELECT `out_patient` FROM `tbl_cmt_premium_master` WHERE `premium_id`='$premium_id'");
								$rowQryA             = mysqli_fetch_row($sqlQryA);
								$out_patient           = empty($rowQryA[0])?" ":$rowQryA[0];*/
								$data.='<td>'.$out_patient.'</td>';
		  }
      $data.='</tr>
       <tr>
        <td>Physiotherapy</td>';
							   $sqlQryAB             = mysqli_query($conn,"SELECT tb2.`company_name`,tb1.`company_id`,tb1.`price_batch_id`,tb1.`premium_id`,tb1.`physiotherapy` FROM `tbl_cmt_ind_companies` tb1 LEFT JOIN `tbl_cmt_ins_company_master` tb2 ON tb1.`company_id`=tb2.`company_id` WHERE tb1.`tr_no`='$tr_no' ORDER BY tb2.`company_name` ASC");
		                        while($row = mysqli_fetch_array($sqlQryAB)){
								$company_id          = $row['company_id'];
								$price_batch_id      = $row['price_batch_id'];
								$premium_id          = $row['premium_id'];
								$physiotherapy       = $row['physiotherapy'];
								/*$sqlQryA             = mysqli_query($conn,"SELECT `physiotherapy` FROM `tbl_cmt_premium_master` WHERE `premium_id`='$premium_id'");
								$rowQryA             = mysqli_fetch_row($sqlQryA);
								$physiotherapy           = empty($rowQryA[0])?" ":$rowQryA[0];*/
								$data.='<td>'.$physiotherapy.'</td>';
		  }
        $data.='</tr>
       <tr>
        <td>Emergency Evacuation</td>';
							   $sqlQryAB             = mysqli_query($conn,"SELECT tb2.`company_name`,tb1.`company_id`,tb1.`price_batch_id`,tb1.`premium_id`,tb1.`emergency_evacuation` FROM `tbl_cmt_ind_companies` tb1 LEFT JOIN `tbl_cmt_ins_company_master` tb2 ON tb1.`company_id`=tb2.`company_id` WHERE tb1.`tr_no`='$tr_no' ORDER BY tb2.`company_name` ASC");
		                        while($row = mysqli_fetch_array($sqlQryAB)){
								$company_id          = $row['company_id'];
								$price_batch_id      = $row['price_batch_id'];
								$premium_id          = $row['premium_id'];
								$emergency_evacuation          = $row['emergency_evacuation'];
								/*$sqlQryA             = mysqli_query($conn,"SELECT `emergency_evacuation` FROM `tbl_cmt_premium_master` WHERE `premium_id`='$premium_id'");
								$rowQryA             = mysqli_fetch_row($sqlQryA);
								$emergency_evacuation           = empty($rowQryA[0])?" ":$rowQryA[0];*/
								$data.='<td>'.$emergency_evacuation.'</td>';
		  }
      $data.='</tr>
        <tr>
        <td>Chronic Conditions</td>';
							   $sqlQryAB             = mysqli_query($conn,"SELECT tb2.`company_name`,tb1.`company_id`,tb1.`price_batch_id`,tb1.`premium_id`,tb1.`chronic_conditions` FROM `tbl_cmt_ind_companies` tb1 LEFT JOIN `tbl_cmt_ins_company_master` tb2 ON tb1.`company_id`=tb2.`company_id` WHERE tb1.`tr_no`='$tr_no' ORDER BY tb2.`company_name` ASC");
		                        while($row = mysqli_fetch_array($sqlQryAB)){
								$company_id          = $row['company_id'];
								$price_batch_id      = $row['price_batch_id'];
								$premium_id          = $row['premium_id'];
								$chronic_conditions          = $row['chronic_conditions'];
								/*$sqlQryA             = mysqli_query($conn,"SELECT `chronic_conditions` FROM `tbl_cmt_premium_master` WHERE `premium_id`='$premium_id'");
								$rowQryA             = mysqli_fetch_row($sqlQryA);
								$chronic_conditions           = empty($rowQryA[0])?" ":$rowQryA[0];*/
								$data.='<td>'.$chronic_conditions.'</td>';
		  }
       $data.='</tr>
      <tr>
       <td>Pre-existing Cover</td>';
							   $sqlQryAB             = mysqli_query($conn,"SELECT tb2.`company_name`,tb1.`company_id`,tb1.`price_batch_id`,tb1.`premium_id`,tb1.`pre_existing_cover` FROM `tbl_cmt_ind_companies` tb1 LEFT JOIN `tbl_cmt_ins_company_master` tb2 ON tb1.`company_id`=tb2.`company_id` WHERE tb1.`tr_no`='$tr_no' ORDER BY tb2.`company_name` ASC");
		                        while($row = mysqli_fetch_array($sqlQryAB)){
								$company_id          = $row['company_id'];
								$price_batch_id      = $row['price_batch_id'];
								$premium_id          = $row['premium_id'];
								$pre_existing_cover          = $row['pre_existing_cover'];
								/*$sqlQryA             = mysqli_query($conn,"SELECT `pre_existing_cover` FROM `tbl_cmt_premium_master` WHERE `premium_id`='$premium_id'");
								$rowQryA             = mysqli_fetch_row($sqlQryA);
								$pre_existing_cover           = empty($rowQryA[0])?" ":$rowQryA[0];*/
								$data.='<td>'.$pre_existing_cover.'</td>';
		  }
      $data.='</tr>
           <tr style="background:#CF9;">
        <td><b>Maternity Benefits</b></td>';
       for($i=0; $i < $cnt_company; $i++){
       $data.='<td></td>';
		  }
       $data.='</tr>
       <tr>
       <td>Routine Maternity</td>';
							   $sqlQryAB             = mysqli_query($conn,"SELECT tb2.`company_name`,tb1.`company_id`,tb1.`price_batch_id`,tb1.`premium_id`,tb1.`routine_maternity` FROM `tbl_cmt_ind_companies` tb1 LEFT JOIN `tbl_cmt_ins_company_master` tb2 ON tb1.`company_id`=tb2.`company_id` WHERE tb1.`tr_no`='$tr_no' ORDER BY tb2.`company_name` ASC");
		                        while($row = mysqli_fetch_array($sqlQryAB)){
								$company_id          = $row['company_id'];
								$price_batch_id      = $row['price_batch_id'];
								$premium_id          = $row['premium_id'];
								$routine_maternity          = $row['routine_maternity'];
								/*$sqlQryA             = mysqli_query($conn,"SELECT `routine_maternity` FROM `tbl_cmt_premium_master` WHERE `premium_id`='$premium_id'");
								$rowQryA             = mysqli_fetch_row($sqlQryA);
								$routine_maternity           = empty($rowQryA[0])?" ":$rowQryA[0];*/
								$data.='<td>'.$routine_maternity.'</td>';
		  }
      $data.='</tr>
       <tr>
       <td>Maternity Waiting Period</td>';
							   $sqlQryAB             = mysqli_query($conn,"SELECT tb2.`company_name`,tb1.`company_id`,tb1.`price_batch_id`,tb1.`premium_id`,tb1.`maternity_waiting_period` FROM `tbl_cmt_ind_companies` tb1 LEFT JOIN `tbl_cmt_ins_company_master` tb2 ON tb1.`company_id`=tb2.`company_id` WHERE tb1.`tr_no`='$tr_no' ORDER BY tb2.`company_name` ASC");
		                        while($row = mysqli_fetch_array($sqlQryAB)){
								$company_id          = $row['company_id'];
								$price_batch_id      = $row['price_batch_id'];
								$premium_id          = $row['premium_id'];
								$maternity_waiting_period          = $row['maternity_waiting_period'];
								/*$sqlQryA             = mysqli_query($conn,"SELECT `maternity_waiting_period` FROM `tbl_cmt_premium_master` WHERE `premium_id`='$premium_id'");
								$rowQryA             = mysqli_fetch_row($sqlQryA);
								$maternity_waiting_period           = empty($rowQryA[0])?" ":$rowQryA[0];*/
								$data.='<td>'.$maternity_waiting_period.'</td>';
		                        }
      $data.='</tr>
       <tr style="background:#CF9;">
        <td><b>Dental Benefits</b></td>';
         for($i=0; $i < $cnt_company; $i++){
          $data.='<td></td>';
		  }
       $data.='</tr>
        <tr>
       <td>Dental</td>';
							   $sqlQryAB             = mysqli_query($conn,"SELECT tb2.`company_name`,tb1.`company_id`,tb1.`price_batch_id`,tb1.`premium_id`,tb1.`dental` FROM `tbl_cmt_ind_companies` tb1 LEFT JOIN `tbl_cmt_ins_company_master` tb2 ON tb1.`company_id`=tb2.`company_id` WHERE tb1.`tr_no`='$tr_no' ORDER BY tb2.`company_name` ASC");
		                        while($row = mysqli_fetch_array($sqlQryAB)){
								$company_id          = $row['company_id'];
								$price_batch_id      = $row['price_batch_id'];
								$premium_id          = $row['premium_id'];
								$dental              = $row['dental'];
								/*$sqlQryA             = mysqli_query($conn,"SELECT `dental` FROM `tbl_cmt_premium_master` WHERE `premium_id`='$premium_id'");
								$rowQryA             = mysqli_fetch_row($sqlQryA);
								$dental           = empty($rowQryA[0])?" ":$rowQryA[0];*/
								$data.='<td>'.$dental.'</td>';
		                        }
      $data.='</tr>
       <tr>
       <td>Dental Waiting Period</td>';
							   $sqlQryAB             = mysqli_query($conn,"SELECT tb2.`company_name`,tb1.`company_id`,tb1.`price_batch_id`,tb1.`premium_id`,tb1.`dental_waiting_period` FROM `tbl_cmt_ind_companies` tb1 LEFT JOIN `tbl_cmt_ins_company_master` tb2 ON tb1.`company_id`=tb2.`company_id` WHERE tb1.`tr_no`='$tr_no' ORDER BY tb2.`company_name` ASC");
		                        while($row = mysqli_fetch_array($sqlQryAB)){
								$company_id          = $row['company_id'];
								$price_batch_id      = $row['price_batch_id'];
								$premium_id          = $row['premium_id'];
								$dental_waiting_period          = $row['dental_waiting_period'];
							/*	$sqlQryA             = mysqli_query($conn,"SELECT `dental_waiting_period` FROM `tbl_cmt_premium_master` WHERE `premium_id`='$premium_id'");
								$rowQryA             = mysqli_fetch_row($sqlQryA);
								$dental_waiting_period           = empty($rowQryA[0])?" ":$rowQryA[0];*/
								$data.='<td>'.$dental_waiting_period.'</td>';
		                        }
        $data.='</tr>
        <tr style="background:#CF9;">
        <td><b>Wellness Benefits</b></td>';
          for($i=0; $i < $cnt_company; $i++){
          $data.='<td></td>';
		  }
       $data.='</tr>
       <tr>
       <td>Optical Benefits</td>';
							   $sqlQryAB             = mysqli_query($conn,"SELECT tb2.`company_name`,tb1.`company_id`,tb1.`price_batch_id`,tb1.`premium_id`,tb1.`optical_benefits`FROM `tbl_cmt_ind_companies` tb1 LEFT JOIN `tbl_cmt_ins_company_master` tb2 ON tb1.`company_id`=tb2.`company_id` WHERE tb1.`tr_no`='$tr_no' ORDER BY tb2.`company_name` ASC");
		                        while($row = mysqli_fetch_array($sqlQryAB)){
								$company_id          = $row['company_id'];
								$price_batch_id      = $row['price_batch_id'];
								$premium_id          = $row['premium_id'];
								$optical_benefits          = $row['optical_benefits'];
								/*$sqlQryA             = mysqli_query($conn,"SELECT `optical_benefits` FROM `tbl_cmt_premium_master` WHERE `premium_id`='$premium_id'");
								$rowQryA             = mysqli_fetch_row($sqlQryA);
								$optical_benefits           = empty($rowQryA[0])?" ":$rowQryA[0];*/
								$data.='<td>'.$optical_benefits.'</td>';
		                        }
     $data.='</tr>
         <tr>
         <td>Wellness</td>';
							   $sqlQryAB             = mysqli_query($conn,"SELECT tb2.`company_name`,tb1.`company_id`,tb1.`price_batch_id`,tb1.`premium_id`,tb1.`wellness` FROM `tbl_cmt_ind_companies` tb1 LEFT JOIN `tbl_cmt_ins_company_master` tb2 ON tb1.`company_id`=tb2.`company_id` WHERE tb1.`tr_no`='$tr_no' ORDER BY tb2.`company_name` ASC");
		                        while($row = mysqli_fetch_array($sqlQryAB)){
								$company_id          = $row['company_id'];
								$price_batch_id      = $row['price_batch_id'];
								$premium_id          = $row['premium_id'];
								$wellness            = $row['wellness'];
							/*	$sqlQryA             = mysqli_query($conn,"SELECT `wellness` FROM `tbl_cmt_premium_master` WHERE `premium_id`='$premium_id'");
								$rowQryA             = mysqli_fetch_row($sqlQryA);
								$wellness           = empty($rowQryA[0])?" ":$rowQryA[0];*/
								$data.='<td>'.$wellness.'</td>';
		                        }
       $data.='</tr>
        <tr style="background:#CF9;">
        <td><b>Payment Information</b></td>';
          for($i=0; $i < $cnt_company; $i++){
           $data.='<td></td>';
		  }
        $data.='</tr>
        <tr>
       <td>Semi Annual Surcharge</td>';
							   $sqlQryAB             = mysqli_query($conn,"SELECT tb2.`company_name`,tb1.`company_id`,tb1.`price_batch_id`,tb1.`premium_id`,tb1.`semi_annual_surcharge` FROM `tbl_cmt_ind_companies` tb1 LEFT JOIN `tbl_cmt_ins_company_master` tb2 ON tb1.`company_id`=tb2.`company_id` WHERE tb1.`tr_no`='$tr_no' ORDER BY tb2.`company_name` ASC");
		                        while($row = mysqli_fetch_array($sqlQryAB)){
								$company_id          = $row['company_id'];
								$price_batch_id      = $row['price_batch_id'];
								$premium_id          = $row['premium_id'];
								$semi_annual_surcharge          = $row['semi_annual_surcharge'];
							/*	$sqlQryA             = mysqli_query($conn,"SELECT `semi_annual_surcharge` FROM `tbl_cmt_premium_master` WHERE `premium_id`='$premium_id'");
								$rowQryA             = mysqli_fetch_row($sqlQryA);
								$semi_annual_surcharge           = empty($rowQryA[0])?" ":$rowQryA[0];*/
								$data.='<td>'.$semi_annual_surcharge.'</td>';
	                           }
       $data.='</tr>
        <tr>
       <td>Quarterly Surcharge</td>';
							   $sqlQryAB             = mysqli_query($conn,"SELECT tb2.`company_name`,tb1.`company_id`,tb1.`price_batch_id`,tb1.`premium_id`,tb1.`quarterly_surcharge` FROM `tbl_cmt_ind_companies` tb1 LEFT JOIN `tbl_cmt_ins_company_master` tb2 ON tb1.`company_id`=tb2.`company_id` WHERE tb1.`tr_no`='$tr_no' ORDER BY tb2.`company_name` ASC");
		                        while($row = mysqli_fetch_array($sqlQryAB)){
								$company_id          = $row['company_id'];
								$price_batch_id      = $row['price_batch_id'];
								$premium_id          = $row['premium_id'];
								$quarterly_surcharge          = $row['quarterly_surcharge'];
						/*		$sqlQryA             = mysqli_query($conn,"SELECT `quarterly_surcharge` FROM `tbl_cmt_premium_master` WHERE `premium_id`='$premium_id'");
								$rowQryA             = mysqli_fetch_row($sqlQryA);
								$quarterly_surcharge           = empty($rowQryA[0])?" ":$rowQryA[0];*/
								$data.='<td>'.$quarterly_surcharge.'</td>';
		                        }
      $data.='</tr>
       <tr>
       <td>Monthly Surcharge</td>';
							   $sqlQryAB             = mysqli_query($conn,"SELECT tb2.`company_name`,tb1.`company_id`,tb1.`price_batch_id`,tb1.`premium_id`,tb1.`monthly_surcharge` FROM `tbl_cmt_ind_companies` tb1 LEFT JOIN `tbl_cmt_ins_company_master` tb2 ON tb1.`company_id`=tb2.`company_id` WHERE tb1.`tr_no`='$tr_no' ORDER BY tb2.`company_name` ASC");
		                        while($row = mysqli_fetch_array($sqlQryAB)){
								$company_id          = $row['company_id'];
								$price_batch_id      = $row['price_batch_id'];
								$premium_id          = $row['premium_id'];
								$monthly_surcharge          = $row['monthly_surcharge'];
								/*$sqlQryA             = mysqli_query($conn,"SELECT `monthly_surcharge` FROM `tbl_cmt_premium_master` WHERE `premium_id`='$premium_id'");
								$rowQryA             = mysqli_fetch_row($sqlQryA);
								$monthly_surcharge           = empty($rowQryA[0])?" ":$rowQryA[0];*/
							    $data.='<td>'.$monthly_surcharge.'</td>';
		                        }
         $data.='</tr>
        <tr style="background:#CF9;">
        <td><b>Members Information</b></td>';
          for($i=0; $i < $cnt_company; $i++){
               $data.='<td></td>';
		  }
        $data.='</tr>';
      $data.='<tr>
       <td>'.$customer_full_name.' ,Age:'.$age_primary.',  '.$gender.'</td>';
							   $sqlQryAB             = mysqli_query($conn,"SELECT `amount` FROM `tbl_cmt_ind_premium_amounts` WHERE `tr_no`='$tr_no' AND `customer_type`='P' ORDER BY `companies_id` ASC");
		                        while($row = mysqli_fetch_array($sqlQryAB)){
							    $amount          = 0;		
								$amount          = $row['amount'];
								
								$data.='<td>AED '.Checkvalid_number_or_not($amount,2).'</td>';
		                        }
      $data.='</tr>';
              $sqlQryAB             = mysqli_query($conn,"SELECT tb1.`dependent_id`,tb2.`dependent_name`,tb2.`dependent_gender`,tb2.`dependent_dob`,tb2.`dependent_marital_status` FROM `tbl_cmt_ind_premium_amounts` tb1 LEFT JOIN `tbl_cmt_ind_dependants` tb2 ON tb1.`dependent_id`=tb1.`dependent_id`  WHERE tb1.`tr_no`='$tr_no' AND tb1.`customer_type`='D' group by tb1.`dependent_id`  ORDER BY tb1.`companies_id` ASC");
		         while($row = mysqli_fetch_array($sqlQryAB)){
				 $dependent_id                          = $row['dependent_id'];
				 $additionl_customer_full_name          = $row['dependent_name'];
				 $additionl_gender                      = $row['dependent_gender'];
				 $additionl_marital_status              = $row['dependent_marital_status'];
				 $dob_secondary  = date('Y',strtotime($row['dependent_dob']));
				 $age_secondary  = (date('Y') - $dob_secondary);
       $data.='<tr>
       <td>'.$additionl_customer_full_name.', Age:'.$age_secondary.',  '.$additionl_gender.'</td>';
							  $sqlQryABC             = mysqli_query($conn,"SELECT `amount` FROM `tbl_cmt_ind_premium_amounts` WHERE `dependent_id`='$dependent_id' AND `tr_no`='$tr_no' AND `customer_type`='D' ORDER BY `companies_id` ASC");
								while($rowABC = mysqli_fetch_array($sqlQryABC)){
								$amount          = 0;		
								$amount          = $rowABC['amount'];
								$data.='<td>AED '.Checkvalid_number_or_not($amount,2).'</td>';
		                        }
                        $data.='</tr>';
                     }
       $data.='<tr style="background:#CF9;">
      <td><b>Total Premium</b></td>';
           for($i=0; $i < $cnt_company; $i++){
          $data.='<td></td>';
		  }
	   $data.='</tr>';   
     $data.='<tr>
       <td>UAE Dirham excluding (TAX) AED</td>';
	                              $m = 0;
							      $sqlQryAB             = mysqli_query($conn,"SELECT tb2.`company_name`,tb1.`company_id`,tb1.`price_batch_id`,tb1.`premium_id` FROM `tbl_cmt_ind_companies` tb1 LEFT JOIN `tbl_cmt_ins_company_master` tb2 ON tb1.`company_id`=tb2.`company_id` WHERE tb1.`tr_no`='$tr_no' ORDER BY tb2.`company_name` ASC");
		                        while($row = mysqli_fetch_array($sqlQryAB)){
								$company_id          = $row['company_id'];
							    $price_batch_id      = $row['price_batch_id'];
								$premium_id          = $row['premium_id'];
								$sqlQryA             = mysqli_query($conn,"SELECT IFNULL(sum(`amount`),0) AS `amount` FROM `tbl_cmt_ind_premium_amounts` WHERE `tr_no`='$tr_no' AND `company_id`='$company_id' AND `price_batch_id`='$price_batch_id' AND `premium_id`='$premium_id' ORDER BY `companies_id` ASC");
								$rowQryA             = mysqli_fetch_row($sqlQryA);
								$amount              = 0;		
								$amount              = $rowQryA['0'];
                                $data.='<td style="background-color:'.$new_array[$m].';color:white;font-weight:bold;">AED '.Checkvalid_number_or_not($amount,2).'</td>';
								$m++;
		      }
		 $data.='</tr>';	  
       $data.='<tr>
       <td>UAE Dirham Including (TAX) AED</td>';
	                            $m = 0;
	                            $sqlQryAB             = mysqli_query($conn,"SELECT tb2.`company_name`,tb1.`company_id`,tb1.`price_batch_id`,tb1.`premium_id` FROM `tbl_cmt_ind_companies` tb1 LEFT JOIN `tbl_cmt_ins_company_master` tb2 ON tb1.`company_id`=tb2.`company_id` WHERE tb1.`tr_no`='$tr_no' ORDER BY tb2.`company_name` ASC");
		                        while($row = mysqli_fetch_array($sqlQryAB)){
								$company_id          = $row['company_id'];
							    $price_batch_id      = $row['price_batch_id'];
								$premium_id          = $row['premium_id'];
								$sqlQryA             = mysqli_query($conn,"SELECT IFNULL(sum(`amount`),0) AS `amount` FROM `tbl_cmt_ind_premium_amounts` WHERE `tr_no`='$tr_no' AND `company_id`='$company_id' AND `price_batch_id`='$price_batch_id' AND `premium_id`='$premium_id' ORDER BY `companies_id` ASC");
								$rowQryA             = mysqli_fetch_row($sqlQryA);
								$amount              = 0;	
								$total_amount        = 0;
								$amount              = $rowQryA['0'];
								$vat_percentage      = .05;
			                    $total_amount        = ($amount + ($amount * $vat_percentage));
                                $data.='<td style="background-color:'.$new_array[$m].';color:white;font-weight:bold;">AED '.Checkvalid_number_or_not($total_amount,2).'</td>';
								$m++;
								}
 $data.='</tr> 
     <tr>
      <td>Comments</td>';
         for($i=0; $i < $cnt_company; $i++){
          $data.='<td></td>';
		    }
			$data.='</tr>';
      $data.='</tbody></table>';

  $data.='</div></div>';

$data.='<br pagebreak="true" /><br /><br /><table width="100%" border="0" cellpadding="1"><tr><td align="left">This is a non-final summary table of benefits and approximate premiums. Premiums offered do not include any local fees, unless otherwise stated, or charges that may apply or change at any time and are subject to
acceptance unless otherwise provided at our sole discretion. On the basis and according to signed enrollment details, the insurance company shall provide the final rate.
<br /><br />The Premiums are quoted in AED unless otherwise provided at our sole discretion. Please note that if any changes or omissions to the benefits are shown in this non-final summary and web listing, the insurance companys policy documents and terms and conditions will take precedence over this summary. We are not responsible for any of the benefit schedules, network lists, exclusions, and insurance company terms and
conditions that may be changed at their own discretion periodically. We kindly recommend that you to check the relevant documents before enrollment.</td></tr></table>';  
$data = utf8_encode($data);
$pdf->writeHTML($data, true, false, true, false, '');     
//=========================last page=============//
$pdf->lastPage();
$pdfnamenew = "invoice_".date("d_m_Y_h_i_s").".pdf";  
ob_end_clean();
$pdf->Output($pdfnamenew, "I");
exit();
}
?>
